### PR TITLE
feat: add `environmentVariables` to `ShellContext`

### PR DESCRIPTION
**Pull request by grant0417**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Additional info:**

### CODE REVIEW

**Comment by grant0417** [comment]
@fedeci, how would we go about adding this field? Tests are failing, seems circular dependant

**Comment by fedeci** [comment]
@grant0417 sounds great to me. I am still refactoring AE so I prefer to wait a little before adding this feature!

**Comment by grant0417** [comment]
Sounds good, I added the value to the `ShellContext` in `@withfig/api-bindings` so it should be easy to add to this `ShellContext` in AE

**Comment by fedeci** [comment]
Totally forgot about this. Reviewing later today!

**Pull request merged**
